### ISSUE TITLE
SSL certificate signed by unknown authority

### ISSUE THREAD

**Issue by jeremy-carbonne** [julien-lafont/Mocky#35]
This project is awesome 👍, but i have an issue with the SSL in strict mode
It's probably the fullchain.pem that is missing

https://www.sslshopper.com/ssl-checker.html#hostname=https://www.mocky.io

**Comment by fabasoad** [comment]
It seems this is a really old issue but I still have it. Trying to request it from `nodejs` app using `got` library but have `GotError: unable to verify the first certificate` error message.

Code:
```javascript
const FormData = require('form-data');
const got = require('got');

module.exports = ({
  body,
  contentType,
  statusCode,
  charset,
  headers
}) => {
  const form = new FormData();
  form.append('statuscode', statusCode);
  form.append('contenttype', contentType);
  form.append('charset', charset);
  form.append('body', body);
  if (headers) {
    Object.keys(headers).forEach(key => {
      form.append('headerNames[]', key);
      form.append('headerValues[]', headers[key]);
    });
  }

  return got.post('https://www.mocky.io/v1', {
    body: form,
    headers: form.getHeaders()
  });
};
```

Error message:
```javascript
GotError: unable to verify the first certificate
      at onError (node_modules\got\dist\source\request-as-event-emitter.js:140:29)
      at handleRequest (node_modules\got\dist\source\request-as-event-emitter.js:173:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
      at TLSSocket._finishInit (_tls_wrap.js:794:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
